<a href="https://colab.research.google.com/github/fernandapetty/data-analytics/blob/techchallenge3-covid19-arquitetura-medalhao-AWS/notebook-ETL-medallion-architecture.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Instalações e imports

In [ ]:
!pip install boto3
!pip install s3fs

Collecting boto3
  Downloading boto3-1.40.39-py3-none-any.whl.metadata (6.7 kB)
Collecting botocore<1.41.0,>=1.40.39 (from boto3)
  Downloading botocore-1.40.39-py3-none-any.whl.metadata (5.7 kB)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3)
  Downloading jmespath-1.0.1-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.15.0,>=0.14.0 (from boto3)
  Downloading s3transfer-0.14.0-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python3.12/dist-packages (from botocore<1.41.0,>=1.40.39->boto3) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /usr/local/lib/python3.12/dist-packages (from botocore<1.41.0,>=1.40.39->boto3) (2.5.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.41.0,>=1.40.39->boto3) (1.17.0)
Downloading boto3-1.40.39-py3-none-any.whl (139 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.3/139.3 kB 5.1 MB/s eta 0:00:00
Downloading botocore-1.40.39-py3-none-any.whl (14.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.0/14.0 MB 135.8 MB/s eta 0:00:00
Downloading jmespath-1.0.1-py3-none-any.whl (20 kB)
Downloading s3transfer-0.14.0-py3-none-any.whl (85 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.7/85.7 kB 7.6 MB/s eta 0:00:00
Installing collected packages: jmespath, botocore, s3transfer, boto3
Successfully installed boto3-1.40.39 botocore-1.40.39 jmespath-1.0.1 s3transfer-0.14.0
Collecting s3fs
  Downloading s3fs-2025.9.0-py3-none-any.whl.metadata (1.4 kB)
Collecting aiobotocore<3.0.0,>=2.5.4 (from s3fs)
  Downloading aiobotocore-2.24.2-py3-none-any.whl.metadata (25 kB)
Collecting fsspec==2025.9.0 (from s3fs)
  Downloading fsspec-2025.9.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from s3fs) (3.12.15)
Collecting aioitertools<1.0.0,>=0.5.1 (from aiobotocore<3.0.0,>=2.5.4->s3fs)
  Downloading aioitertools-0.12.0-py3-none-any.whl.metadata (3.8 kB)
Collecting botocore<1.40.19,>=1.40.15 (from aiobotocore<3.0.0,>=2.5.4->s3fs)
  Downloading botocore-1.40.18-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python3.12/dist-packages (from aiobotocore<3.0.0,>=2.5.4->s3fs) (2.9.0.post0)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from aiobotocore<3.0.0,>=2.5.4->s3fs) (1.0.1)
Requirement already satisfied: multidict<7.0.0,>=6.0.0 in /usr/local/lib/python3.12/dist-packages (from aiobotocore<3.0.0,>=2.5.4->s3fs) (6.6.4)
Requirement already satisfied: wrapt<2.0.0,>=1.10.10 in /usr/local/lib/python3.12/dist-packages (from aiobotocore<3.0.0,>=2.5.4->s3fs) (1.17.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs) (1.7.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs) (1.20.1)
Requirement already satisfied: typing-extensions>=4.2 in /usr/local/lib/python3.12/dist-packages (from aiosignal>=1.4.0->aiohttp!=4.0.0a0,!=4.0.0a1->s3fs) (4.15.0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /usr/local/lib/python3.12/dist-packages (from botocore<1.40.19,>=1.40.15->aiobotocore<3.0.0,>=2.5.4->s3fs) (2.5.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil<3.0.0,>=2.1->aiobotocore<3.0.0,>=2.5.4->s3fs) (1.17.0)
Requirement already satisfied: idna>=2.0 in /usr/local/lib/python3.12/dist-packages (from yarl<2.0,>=1.17.0->aiohttp!=4.0.0a0,!=4.0.0a1->s3fs) (3.10)
Downloading s3fs-2025.9.0-py3-none-any.whl (30 kB)
Downloading fsspec-2025.9.0-py3-none-any.whl (199 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.3/199.3 kB 12.8 MB/s eta 0:00:00
Downloading aiobotocore-2.24.2-py3-none-any.whl (85 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.4/85.4 kB 5.7 MB/s eta 0:00:00
Downloading aioitertools-0.12.0-py3-none-any.whl (24 kB)
Downloading botocore-1.40.18-py3-none-any.whl (14.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.0/14.0 MB 102.6 MB/s eta 0:00:00
Installing collected packages: fsspec, aioitertools, botocore, aiobotocore, s3fs
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2025.3.0
    Uninstalling fsspec-2025.3.0:
      Successfully uninstalled fsspec-2025.3.0
  Attempting uninstall: botocore
    Found existing installation: botocore 1.40.39
    Uninstalling botocore-1.40.39:
      Successfully uninstalled botocore-1.40.39
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
boto3 1.40.39 requires botocore<1.41.0,>=1.40.39, but you have botocore 1.40.18 which is incompatible.
gcsfs 2025.3.0 requires fsspec==2025.3.0, but you have fsspec 2025.9.0 which is incompatible.
datasets 4.0.0 requires fsspec[http]<=2025.3.0,>=2023.1.0, but you have fsspec 2025.9.0 which is incompatible.
Successfully installed aiobotocore-2.24.2 aioitertools-0.12.0 botocore-1.40.18 fsspec-2025.9.0 s3fs-2025.9.0

In [ ]:
# Imports
import requests
import zipfile
import io
import pandas as pd
import os
import boto3
import sys
import time

from dotenv import load_dotenv
from sqlalchemy import create_engine, text
from botocore.exceptions import BotoCoreError, ClientError
from psycopg2 import sql

# Variáveis e configurações de ambiente

In [ ]:
# Bucket S3
s3_bucket = '905418227640'
s3_bucket_folder = 'data-input/covid19'

caminho_saida_silver = f's3://{s3_bucket}/data-output/silver-pnad_consolidado_enriquecido.parquet'
caminho_saida_gold = f's3://{s3_bucket}/data-output/gold-pnad_final_tratado.parquet'

codigo_uf_file = '/data-input/codigo_uf.csv'

# Nome da tabela no PostgreSQL
nome_tabela = 'questionario'

In [ ]:
# Configuração conexao AWS
AWS_access_key_id = "ASIA5FTZBX64OTDCYFNT"
AWS_secret_access_key = "6glVCtkizBLyUdEDIGuMZ47OWsNuS9bCJg6CMTEt"
AWS_session_token = "IQoJb3JpZ2luX2VjEAsaCXVzLXdlc3QtMiJHMEUCIESguIyWgLUoi/05h6/Mbs0vc092hnCMiB/sWVDYaM2qAiEAi/tQXwscwR4hjE7hXTBk//z+n2JaMLtaoJOmOXVpXksqugIIlP//////////ARAAGgw5MDU0MTgyMjc2NDAiDDFKbpjDFEaQ1zCityqOAnwgrx6mtmknwiBW9Nl9lpeyFgWVPSQ38FSloR2SdWV2fyZjPla3BKe0zr7EkDlI5bdo1u4z06Z5Am6bGSkVbwNXtXvX4X2w1hGtPv55h1KdEKJy51YXI2qE6Fon2/VvDKYOCNmHA7qib83u7fsIRNwPuE3xf8cIm2pF8GNrrYmNNVyhcmOOt3cNhWx5LcKG4gROzgofFYuHx0S7GqgI9HRIBtRdOcqgvQ75MhGVGd2rhcDeXtO1+rEF7wbut9CIDF2wLSkcGal+oXs71YvZBzfuLzl2jGBGAh4iO0iheKi9ppL3DUbdKEqfUOwn8R0DncaOBBpvjF7biJZlb7AK30VF8vq8X8gkCUermyd1nTD+wtvGBjqdAb1S5s4VF6dXqjsBZFWOzwVkRQIysVraasPcyhr4LLtzSc+MA/ZpN1iPQ6YOcMvIBgQYOheN3iPOGIcWn1HJsunvfhU5r9go0TnnHyDoMrIJbjiDrtfsgtZk8WRINBR4+UYv+70mc5TJo54pC3RTesiHQztka2Rhgu70BdhR/1cuK9yJFAbK2kyUdbSiWxH6r7mJaaTxUJCHtukU97Y="
Region_name = "sa-east-1"


storage_options = {
    "key": AWS_access_key_id,
    "secret": AWS_secret_access_key,
    "token": AWS_session_token
}

# Credenciais do PostgreSQL
usuario_pg = "postgres"
senha_pg = "TechFiapTechFiap"
host_pg = "postgres-db.c3o4yi8i6o3f.us-east-1.rds.amazonaws.com"
porta_pg = "5432"
banco_pg = "postgres"

# Conexão Banco de dados AWS - PostgreSQL

In [ ]:
# Checar a conexão bd
def test_connection(engine):

    try:
        with engine.connect() as connection:

            # Testar a versão do PostgreSQL
            result = connection.execute(text("SELECT version();"))
            versao = result.fetchone()
            print("✅ Conectado com sucesso:", versao[0])

            # Listar as tabelas no schema público
            result = connection.execute(text("""
                SELECT table_name
                FROM information_schema.tables
                WHERE table_schema = 'public';
            """))
            tabelas = result.fetchall()
            print("📄 Tabelas no banco:")
            for tabela in tabelas:
                print("-", tabela[0])

    except Exception as e:
        print("❌ Erro ao executar comandos:", e)
        sys.exit()

In [ ]:
# Criar engine com banco
engine = create_engine(f"postgresql+psycopg2://{usuario_pg}:{senha_pg}@{host_pg}:{porta_pg}/{banco_pg}")

# Testar a conexão
test_connection(engine)

✅ Conectado com sucesso: PostgreSQL 17.4 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 12.4.0, 64-bit
📄 Tabelas no banco:
- questionario

# Conexão AWS

In [ ]:
# Conexão AWS
try:
    client = boto3.client(
        'sts',
        aws_access_key_id = AWS_access_key_id,
        aws_secret_access_key = AWS_secret_access_key,
        aws_session_token = AWS_session_token,
        region_name = Region_name
    )

    identity = client.get_caller_identity()
    print("✅ Conectado à conta\n")
    print("UserId:", identity["UserId"])
    print("Account:", identity["Account"])
    print("Arn:", identity["Arn"])

except (BotoCoreError, ClientError) as e:
    print("❌ Erro ao conectar à AWS. Verifique suas credenciais e tente novamente.")
    print("Detalhes do erro:", e)

✅ Conectado à conta

UserId: AROA5FTZBX64E4JUQHAGG:user4394146=fernandapetty@gmail.com
Account: 905418227640
Arn: arn:aws:sts::905418227640:assumed-role/voclabs/user4394146=fernandapetty@gmail.com

# CAMADA BRONZE - Leitura arquivos bucket S3 AWS

Leitura csv UF + criação df_uf

In [ ]:
# Create an S3 client
s3_client = boto3.client(
    's3',
    aws_access_key_id=AWS_access_key_id,
    aws_secret_access_key=AWS_secret_access_key,
    aws_session_token=AWS_session_token,
    region_name=Region_name
)

s3_client.head_bucket(Bucket=s3_bucket)
response_uf = s3_client.list_objects_v2(Bucket=s3_bucket, Prefix=f'{codigo_uf_file}/') # Listar todos os objetos (arquivos) dentro do S3

file_path = f"s3://{s3_bucket}{codigo_uf_file}"
df_uf = pd.read_csv(file_path, storage_options=storage_options, sep=',')

Leitura arquivos covid + criacao data frames dados não tratados

In [ ]:
# Ler arquivos CSV PNAD COVID do S3, consolidar e gerar Data Frame
response = s3_client.list_objects_v2(Bucket=s3_bucket, Prefix=f'{s3_bucket_folder}/') # Listar todos os objetos (arquivos) dentro do S3
bronze_files = [obj['Key'] for obj in response.get('Contents', []) if obj['Key'].endswith('.csv')] # Pegar apenas arquivos .csv
lista_de_dataframes = []

print("Lendo arquivos da camada Bronze no S3")
print(bronze_files)

# Iterar sobre os arquivos
for file_key in bronze_files:

    file_path = f"s3://{s3_bucket}/{file_key}"
    print(f"Lendo {file_path}")
    df_temp = pd.read_csv(file_path, storage_options=storage_options, sep=',')
    lista_de_dataframes.append(df_temp)

Lendo arquivos da camada Bronze no S3
['data-input/covid19/PNAD_COVID_052020.csv', 'data-input/covid19/PNAD_COVID_072020.csv', 'data-input/covid19/PNAD_COVID_102020.csv']
Lendo s3://905418227640/data-input/covid19/PNAD_COVID_052020.csv
Lendo s3://905418227640/data-input/covid19/PNAD_COVID_072020.csv
Lendo s3://905418227640/data-input/covid19/PNAD_COVID_102020.csv

# CAMADA SILVER - dataframe consolidado

In [ ]:
# Carregar dados para camada silver

# Consolidar os data frame
df_consolidado = pd.concat(lista_de_dataframes, ignore_index=True)
print(f"\nConsolidação concluída e {len(df_consolidado)} linhas lidas da camada Bronze")

# Relacionar os Data Frame
print("\nIniciando enriquecimento dos dados com merge com o Data Frame df_uf")
df_silver = pd.merge(
    df_consolidado,
    df_uf,
    how='left',
    left_on='UF',
    right_on='Código'
)

# Remover colunas não necessarias e ajustar o nome das colunas
df_silver = df_silver.drop(columns=["Código"])
df_silver = df_silver.rename(columns={"UF_x": "UF", "UF_y": "UF_Nome", "Região": "Regiao"})
print("Enriquecimento concluído")

# Ver o resultado final
display(df_silver.head(5))

Consolidação concluída e 1113933 linhas lidas da camada Bronze

Iniciando enriquecimento dos dados com merge com o Data Frame df_uf
Enriquecimento concluído

,Ano,UF,CAPITAL,RM_RIDE,V1008,V1012,V1013,V1016,Estrato,UPA,...,E0023,E0024,F002A1,F002A2,F002A3,F002A4,F002A5,UF_Nome,Sigla,Regiao
0,2020,11,11.0,NaN,1,4,5,1,1110011,110015970,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rondônia,RO,Norte
1,2020,11,11.0,NaN,1,4,5,1,1110011,110015970,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rondônia,RO,Norte
2,2020,11,11.0,NaN,1,4,5,1,1110011,110015970,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rondônia,RO,Norte
3,2020,11,11.0,NaN,1,4,5,1,1110011,110015970,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rondônia,RO,Norte
4,2020,11,11.0,NaN,3,2,5,1,1110011,110015970,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rondônia,RO,Norte

In [ ]:
# Salvar Data Frame df_silver na camada silver
print(f"\nSalvando dados da camada Silver em: {caminho_saida_silver}")

df_silver.to_parquet(
    caminho_saida_silver,
    index=False,
    storage_options=storage_options
)

print("✅ Sucesso! Camada Silver criada e salva no S3")

Salvando dados da camada Silver em: s3://905418227640/data-output/silver-pnad_consolidado_enriquecido.parquet
✅ Sucesso! Camada Silver criada e salva no S3

# CAMADA GOLD - envio dos dados tratados para o banco de dados

In [ ]:
# Tratar os dados para a camada Gold
print(f"Lendo dados da camada Silver de: {caminho_saida_silver}")

try:
    df_silver = pd.read_parquet(caminho_saida_silver, storage_options=storage_options)
    print(f"Leitura concluída onde o dataFrame contem {len(df_silver)} linhas e {len(df_silver.columns)} colunas")

except Exception as e:
    print(f"❌ Erro ao ler o arquivo da camada Silver. Verifique o caminho e as permissões. Detalhes: {e}")
    sys.exit()

# Copiar e padronizar colunas para minúsculas
df_estruturado = df_silver.copy()
df_estruturado.columns = df_estruturado.columns.str.lower()

# Colunas fixas (com descrição)
colunas_fixas = [
    'ano',       # Ano
    'v1013',     # Mês do Ano
    'v1012',     # Semana do Mês
    'uf',        # Sigla da Unidade da Federação
    'capital',   # Capital do Estado
    'rm_ride',   # Região Metropolitana e Região Administrativa Integrada de Desenvolvimento
    'uf_nome',   # Nome do UF
    'sigla',     # Sigla do UF
    'regiao',    # Região
]

# Colunas desejadas (com descrição)
colunas_desejadas = [
    'a002',      # Idade
    'a003',      # Sexo
    'a004',      # Raça ou Cor
    'a006b',     # Você está tendo aulas presenciais?
    'b008',      # O(A) Sr(a) fez algum teste para saber se estava infectado(a) pelo coronavírus?
    'b009a',     # Fez o exame coletado com cotonete na boca e/ou nariz (SWAB)?
    'b009c',     # Fez o exame de coleta de sangue através de furo no dedo?
    'b009e',     # Fez o exame de coleta de sangue através da veia do braço?
    'a005',      # Escolaridade
    'a006',      # Frequenta escola
    'a006a',     # A escola/faculdade que frequenta é pública ou privada?
    'b0011',     # Na semana passada teve febre?
    'b0012',     # Na semana passada teve tosse?
    'b0013',     # Na semana passada teve dor de garganta?
    'b0014',     # Na semana passada teve dificuldade para respirar?
    'b0015',     # Na semana passada teve dor de cabeça?
    'b0016',     # Na semana passada teve dor no peito?
    'b0017',     # Na semana passada teve náusea?
    'b0018',     # Na semana passada teve nariz entupido ou escorrendo?
    'b0019',     # Na semana passada teve fadiga?
    'b00110',    # Na semana passada teve dor nos olhos?
    'b00111',    # Na semana passada teve perda de cheiro ou sabor?
    'b00112',    # Na semana passada teve dor muscular?
    'b00113',    # Na semana passada teve diarreia?
]

# Unir listas mantendo a ordem e sem duplicar
todas_colunas = list(dict.fromkeys([*colunas_fixas, *colunas_desejadas]))

# Manter apenas as colunas que existem no DataFrame após padronização
colunas_existentes = [c for c in todas_colunas if c in df_estruturado.columns]

# Filtro com os 3 últimos valores de v1013
if 'v1013' in df_estruturado.columns:
    # Coletar valores únicos (excluindo NaN), ordenar e pegar os 3 últimos
    ultimos_3 = sorted(pd.unique(df_estruturado['v1013'].dropna()))[-3:]

    # Filtrar registros pertencentes aos 3 últimos meses e selecionar colunas
    estrutura_final = (
        df_estruturado[df_estruturado['v1013'].isin(ultimos_3)][colunas_existentes]
        .reset_index(drop=True)
    )
else:
    # Se não houver v1013, apenas seleciona as colunas existentes
    estrutura_final = df_estruturado[colunas_existentes].reset_index(drop=True)

# Avisos sobre colunas ausentes
faltantes = [c for c in todas_colunas if c not in df_estruturado.columns]
if faltantes:
    print(f"Atenção: estas colunas não foram encontradas e ficaram de fora: {faltantes}")

# Ver o resultado final
print("\nData Frame com os primeiros registros")
display(estrutura_final.head(5))

print("Data Frame com os ultimos registros")
display(estrutura_final.tail(5))

Lendo dados da camada Silver de: s3://905418227640/data-output/silver-pnad_consolidado_enriquecido.parquet
Leitura concluída onde o dataFrame contem 1113933 linhas e 148 colunas
Atenção: estas colunas não foram encontradas e ficaram de fora: ['a006b', 'a006a']

Data Frame com os primeiros registros

,ano,v1013,v1012,uf,capital,rm_ride,uf_nome,sigla,regiao,a002,...,b0014,b0015,b0016,b0017,b0018,b0019,b00110,b00111,b00112,b00113
0,2020,5,4,11,11.0,NaN,Rondônia,RO,Norte,35,...,2,1,2,2,2,2,2,1,2,NaN
1,2020,5,4,11,11.0,NaN,Rondônia,RO,Norte,29,...,2,2,2,2,2,2,2,1,2,NaN
2,2020,5,4,11,11.0,NaN,Rondônia,RO,Norte,13,...,2,2,2,2,2,2,2,2,2,NaN
3,2020,5,4,11,11.0,NaN,Rondônia,RO,Norte,10,...,2,2,2,2,2,2,2,2,2,NaN
4,2020,5,2,11,11.0,NaN,Rondônia,RO,Norte,58,...,2,2,2,2,2,2,2,2,2,NaN

Data Frame com os ultimos registros

,ano,v1013,v1012,uf,capital,rm_ride,uf_nome,sigla,regiao,a002,...,b0014,b0015,b0016,b0017,b0018,b0019,b00110,b00111,b00112,b00113
1113928,2020,10,3,53,53.0,NaN,Distrito Federal,DF,Centro-Oeste,45,...,2,2,2,2,2,2,2,2,2,2.0
1113929,2020,10,3,53,53.0,NaN,Distrito Federal,DF,Centro-Oeste,22,...,2,2,2,2,2,2,2,2,2,2.0
1113930,2020,10,3,53,53.0,NaN,Distrito Federal,DF,Centro-Oeste,16,...,2,2,2,2,2,2,2,2,2,2.0
1113931,2020,10,2,53,53.0,NaN,Distrito Federal,DF,Centro-Oeste,83,...,2,2,2,2,2,2,2,2,2,2.0
1113932,2020,10,2,53,53.0,NaN,Distrito Federal,DF,Centro-Oeste,75,...,2,2,2,2,2,2,2,2,2,2.0

In [ ]:
# Carregar os dados para a Gold
print(f"\nSalvando dados da camada Gold em: {caminho_saida_gold}")

# Salvar o data frame como .parquet
estrutura_final.to_parquet(
    caminho_saida_gold,
    index=False,
    storage_options=storage_options # Parametro necessario para conseguir conectar o Pandas ao AWS
)

print(f"✅ Sucesso! Camada Gold criada com {len(estrutura_final)} linhas e salva no S3.")

Salvando dados da camada Gold em: s3://905418227640/data-output/gold-pnad_final_tratado.parquet
✅ Sucesso! Camada Gold criada com 1113933 linhas e salva no S3.

In [ ]:
# Criar a tabela no banco de dados PostgreSQL
print("Iniciando a criação do esquema da tabela")

try:
    df_schema = estrutura_final.head(0)
    df_schema.to_sql(
        nome_tabela,
        con=engine,
        if_exists='replace', # Dropar a tabela
        index=False)

    print(f"✅ Esquema da tabela '{nome_tabela}' criado com sucesso no PostgreSQL!")

    # Adicionar colunas padrão de carga com valores DEFAULT
    print("\nAdicionando colunas de metadados (data_hora_carga, usuario_carga)")

    with engine.connect() as connection:
        comando_sql_data = text(f"""
            ALTER TABLE {nome_tabela}
            ADD COLUMN data_hora_carga TIMESTAMPTZ DEFAULT NOW();
        """)

        comando_sql_usuario = text(f"""
            ALTER TABLE {nome_tabela}
            ADD COLUMN usuario_carga VARCHAR(255) DEFAULT CURRENT_USER;
        """)

        connection.execute(comando_sql_data)
        connection.execute(comando_sql_usuario)
        connection.commit()

        print(f"✅ Colunas de metadados adicionadas com sucesso à tabela '{nome_tabela}'.")

except Exception as e:
    print(f"❌ Erro durante a criação ou alteração da tabela: {e}")
    sys.exit()

Iniciando a criação do esquema da tabela
✅ Esquema da tabela 'questionario' criado com sucesso no PostgreSQL!

Adicionando colunas de metadados (data_hora_carga, usuario_carga)
✅ Colunas de metadados adicionadas com sucesso à tabela 'questionario'.

In [ ]:
# Carregar dados da Gold para PostgreSQL
with engine.connect() as connection:
    try:
        print(f"Lendo dados de: {caminho_saida_gold }")
        df_gold = pd.read_parquet(caminho_saida_gold , storage_options=storage_options)
        print(f"Leitura concluída. DataFrame com {len(df_gold)} linhas.")

        # Obtemos a conexão do psycopg2 a partir da conexão da engine
        raw_conn = connection.connection
        cursor = raw_conn.cursor()

        # Truncar a tabela
        print(f"Limpando a tabela de destino '{nome_tabela}'")
        truncate_query = sql.SQL("TRUNCATE TABLE {}").format(sql.Identifier(nome_tabela))
        cursor.execute(truncate_query)

        # Carregar os dados via COPY
        buffer = io.StringIO()
        df_gold.to_csv(buffer, index=False, header=False, sep='\t')
        buffer.seek(0)
        print(f"Iniciando a carga de {len(df_gold)} linhas via COPY")
        colunas_df = list(df_gold.columns)
        cursor.copy_from(buffer, nome_tabela, sep='\t', null='', columns=colunas_df)
        print("Carga via COPY concluída")
        raw_conn.commit()
        cursor.close()
        print(f"✅ Sucesso! Transação efetivada na tabela '{nome_tabela}'")

        print("\nProcesso concluído com sucesso!")

    except Exception as e:
        print(f"❌ Ocorreu um erro durante o processo: {e}")
        if 'raw_conn' in locals() and not raw_conn.closed:
             raw_conn.rollback()
             print("Transação revertida (rollback).")

Lendo dados de: s3://905418227640/data-output/gold-pnad_final_tratado.parquet
Leitura concluída. DataFrame com 1113933 linhas.
Limpando a tabela de destino 'questionario'
Iniciando a carga de 1113933 linhas via COPY
Carga via COPY concluída
✅ Sucesso! Transação efetivada na tabela 'questionario'

Iniciando a exportação dos dados da tabela para .csv
✅ Dados exportados com sucesso!
Localização: /content/questionario_exportado.csv

Processo concluído com sucesso!